export const FETCH_COUNTRIES = 'FETCH_COUNTRIES';
export const FETCH_COUNTRIES_SUCCESS = 'FETCH_COUNTRIES_SUCCESS';
export const FETCH_COUNTRIES_FAILURE = 'FETCH_COUNTRIES_FAILURE';

export const SAVE_POPULATION = 'SAVE_POPULATION';
export const DELETE_COUNTRY = 'DELETE_COUNTRY';
